meta_product_name: "The Good Car"
meta_title: "The Good Car"
meta_description: "What's you've always been missing"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
